In [48]:
import pandas as pd
import numpy as np
import xgboost as xgb
from sklearn.model_selection import train_test_split
from sklearn.metrics import balanced_accuracy_score, roc_auc_score, make_scorer # for scoring during
from sklearn.model_selection import GridSearchCV # cross validation
from sklearn.metrics import confusion_matrix # creates a confusion matrix
from sklearn.metrics import ConfusionMatrixDisplay

In [49]:
import sqlite3
conn = sqlite3.connect("cbb.db")
df_raw = pd.read_csv("cbb.csv")
df_raw.to_sql("teams", conn, index=False, if_exists="replace")

4249

In [50]:
q = """
SELECT TEAM, YEAR, G, W, SEED, BARTHAG,
CASE WHEN POSTSEASON = 'Champions' THEN 1 ELSE 0 END AS champion
FROM teams
WHERE POSTSEASON IS NOT NULL
ORDER BY champion DESC, YEAR DESC
"""

check = pd.read_sql(q, conn)
check.head(15)

              TEAM  YEAR   G   W  SEED  BARTHAG  champion
0          Florida  2025  40  36   1.0   0.9709         1
1      Connecticut  2024  34  31   1.0   0.9712         1
2      Connecticut  2023  39  31   4.0   0.9643         1
3           Kansas  2022  40  34   1.0   0.9580         1
4           Baylor  2021  24  22   1.0   0.9548         1
5         Virginia  2019  38  35   1.0   0.9736         1
6        Villanova  2018  40  36   1.0   0.9725         1
7   North Carolina  2017  39  33   1.0   0.9615         1
8        Villanova  2016  40  35   2.0   0.9703         1
9             Duke  2015  39  35   1.0   0.9764         1
10     Connecticut  2014  40  32   7.0   0.9171         1
11      Louisville  2013  40  35   1.0   0.9743         1
12         Houston  2025  40  35   1.0   0.9836         0
13            Duke  2025  39  35   1.0   0.9824         0
14          Auburn  2025  38  32   1.0   0.9746         0

In [51]:
lookup = pd.DataFrame(
    [(k, v[0], v[1]) for k, v in tourney.items()],
    columns=["finish", "t_games", "t_wins"])
lookup.to_sql("tourney_lookup", conn, index=False, if_exists="replace")

lookup.head()

      finish  t_games  t_wins
0  Champions        6       6
1        2ND        6       5
2         F4        5       4
3         E8        4       3
4        S16        3       2

In [64]:
q = """
SELECT *
FROM teams t
LEFT JOIN tourney_lookup l ON t.POSTSEASON = l.finish
"""

sql_df = pd.read_sql(q, conn)
sql_df.head()

,TEAM,CONF,G,W,ADJOE,ADJDE,BARTHAG,EFG_O,EFG_D,TOR,TORD,ORB,DRB,FTR,FTRD,2P_O,2P_D,3P_O,3P_D,ADJ_T,WAB,POSTSEASON,SEED,YEAR,finish,t_games,t_wins
0,North Carolina,ACC,40,33,123.3,94.9,0.9531,52.6,48.1,15.4,18.2,40.7,30.0,32.3,30.4,53.9,44.6,32.7,36.2,71.7,8.6,2ND,1.0,2016,2ND,6.0,5.0
1,Wisconsin,B10,40,36,129.1,93.6,0.9758,54.8,47.7,12.4,15.8,32.1,23.7,36.2,22.4,54.8,44.7,36.5,37.5,59.3,11.3,2ND,1.0,2015,2ND,6.0,5.0
2,Michigan,B10,40,33,114.4,90.4,0.9375,53.9,47.7,14.0,19.5,25.5,24.9,30.7,30.0,54.7,46.8,35.2,33.2,65.9,6.9,2ND,3.0,2018,2ND,6.0,5.0
3,Texas Tech,B12,38,31,115.2,85.2,0.9696,53.5,43.0,17.7,22.8,27.4,28.7,32.9,36.6,52.8,41.9,36.5,29.7,67.5,7.0,2ND,3.0,2019,2ND,6.0,5.0
4,Gonzaga,WCC,39,37,117.8,86.3,0.9728,56.6,41.1,16.2,17.1,30.0,26.2,39.0,26.9,56.3,40.0,38.2,29.0,71.5,7.7,2ND,1.0,2017,2ND,6.0,5.0

In [63]:
q = """
SELECT * 
FROM teams t 
LIMIT 10
"""

test = pd.read_sql(q, conn)
test.head()

,TEAM,CONF,G,W,ADJOE,ADJDE,BARTHAG,EFG_O,EFG_D,TOR,TORD,ORB,DRB,FTR,FTRD,2P_O,2P_D,3P_O,3P_D,ADJ_T,WAB,POSTSEASON,SEED,YEAR
0,North Carolina,ACC,40,33,123.3,94.9,0.9531,52.6,48.1,15.4,18.2,40.7,30.0,32.3,30.4,53.9,44.6,32.7,36.2,71.7,8.6,2ND,1.0,2016
1,Wisconsin,B10,40,36,129.1,93.6,0.9758,54.8,47.7,12.4,15.8,32.1,23.7,36.2,22.4,54.8,44.7,36.5,37.5,59.3,11.3,2ND,1.0,2015
2,Michigan,B10,40,33,114.4,90.4,0.9375,53.9,47.7,14.0,19.5,25.5,24.9,30.7,30.0,54.7,46.8,35.2,33.2,65.9,6.9,2ND,3.0,2018
3,Texas Tech,B12,38,31,115.2,85.2,0.9696,53.5,43.0,17.7,22.8,27.4,28.7,32.9,36.6,52.8,41.9,36.5,29.7,67.5,7.0,2ND,3.0,2019
4,Gonzaga,WCC,39,37,117.8,86.3,0.9728,56.6,41.1,16.2,17.1,30.0,26.2,39.0,26.9,56.3,40.0,38.2,29.0,71.5,7.7,2ND,1.0,2017

In [ ]:
df = pd.read_csv("cbb.csv")
pd.set_option("display.max_columns", None)

In [ ]:
df.head()

,TEAM,CONF,G,W,ADJOE,ADJDE,BARTHAG,EFG_O,EFG_D,TOR,TORD,ORB,DRB,FTR,FTRD,2P_O,2P_D,3P_O,3P_D,ADJ_T,WAB,POSTSEASON,SEED,YEAR
0,North Carolina,ACC,40,33,123.3,94.9,0.9531,52.6,48.1,15.4,18.2,40.7,30.0,32.3,30.4,53.9,44.6,32.7,36.2,71.7,8.6,2ND,1.0,2016
1,Wisconsin,B10,40,36,129.1,93.6,0.9758,54.8,47.7,12.4,15.8,32.1,23.7,36.2,22.4,54.8,44.7,36.5,37.5,59.3,11.3,2ND,1.0,2015
2,Michigan,B10,40,33,114.4,90.4,0.9375,53.9,47.7,14.0,19.5,25.5,24.9,30.7,30.0,54.7,46.8,35.2,33.2,65.9,6.9,2ND,3.0,2018
3,Texas Tech,B12,38,31,115.2,85.2,0.9696,53.5,43.0,17.7,22.8,27.4,28.7,32.9,36.6,52.8,41.9,36.5,29.7,67.5,7.0,2ND,3.0,2019
4,Gonzaga,WCC,39,37,117.8,86.3,0.9728,56.6,41.1,16.2,17.1,30.0,26.2,39.0,26.9,56.3,40.0,38.2,29.0,71.5,7.7,2ND,1.0,2017

In [ ]:
df.shape

(4249, 24)

In [ ]:
df.dtypes

TEAM              str
CONF              str
G               int64
W               int64
ADJOE         float64
ADJDE         float64
BARTHAG       float64
EFG_O         float64
EFG_D         float64
TOR           float64
TORD          float64
ORB           float64
DRB           float64
FTR           float64
FTRD          float64
2P_O          float64
2P_D          float64
3P_O          float64
3P_D          float64
ADJ_T         float64
WAB           float64
POSTSEASON        str
SEED          float64
YEAR            int64
dtype: object

In [ ]:
df.isna().sum()

TEAM             0
CONF             0
G                0
W                0
ADJOE            0
ADJDE            0
BARTHAG          0
EFG_O            0
EFG_D            0
TOR              0
TORD             0
ORB              0
DRB              0
FTR              0
FTRD             0
2P_O             0
2P_D             0
3P_O             0
3P_D             0
ADJ_T            0
WAB              0
POSTSEASON    3433
SEED          3433
YEAR             0
dtype: int64

In [ ]:
df.value_counts("POSTSEASON")

POSTSEASON
R64          384
R32          192
S16           96
E8            48
R68           48
F4            24
2ND           12
Champions     12
Name: count, dtype: int64

In [ ]:
df = df[df["POSTSEASON"].notna()].copy()

In [ ]:
X = df.drop(columns="TEAM")

In [ ]:
X.head()

,CONF,G,W,ADJOE,ADJDE,BARTHAG,EFG_O,EFG_D,TOR,TORD,ORB,DRB,FTR,FTRD,2P_O,2P_D,3P_O,3P_D,ADJ_T,WAB,POSTSEASON,SEED,YEAR
0,ACC,40,33,123.3,94.9,0.9531,52.6,48.1,15.4,18.2,40.7,30.0,32.3,30.4,53.9,44.6,32.7,36.2,71.7,8.6,2ND,1.0,2016
1,B10,40,36,129.1,93.6,0.9758,54.8,47.7,12.4,15.8,32.1,23.7,36.2,22.4,54.8,44.7,36.5,37.5,59.3,11.3,2ND,1.0,2015
2,B10,40,33,114.4,90.4,0.9375,53.9,47.7,14.0,19.5,25.5,24.9,30.7,30.0,54.7,46.8,35.2,33.2,65.9,6.9,2ND,3.0,2018
3,B12,38,31,115.2,85.2,0.9696,53.5,43.0,17.7,22.8,27.4,28.7,32.9,36.6,52.8,41.9,36.5,29.7,67.5,7.0,2ND,3.0,2019
4,WCC,39,37,117.8,86.3,0.9728,56.6,41.1,16.2,17.1,30.0,26.2,39.0,26.9,56.3,40.0,38.2,29.0,71.5,7.7,2ND,1.0,2017

In [ ]:
X = pd.get_dummies(X, columns=["CONF"], dtype = int)

In [ ]:
X.head()

,G,W,ADJOE,ADJDE,BARTHAG,EFG_O,EFG_D,TOR,TORD,ORB,DRB,FTR,FTRD,2P_O,2P_D,3P_O,3P_D,ADJ_T,WAB,POSTSEASON,SEED,YEAR,CONF_A10,CONF_ACC,CONF_AE,CONF_ASun,CONF_Amer,CONF_B10,CONF_B12,CONF_BE,CONF_BSky,CONF_BSth,CONF_BW,CONF_CAA,CONF_CUSA,CONF_Horz,CONF_Ivy,CONF_MAAC,CONF_MAC,CONF_MEAC,CONF_MVC,CONF_MWC,CONF_NEC,CONF_OVC,CONF_P12,CONF_Pat,CONF_SB,CONF_SC,CONF_SEC,CONF_SWAC,CONF_Slnd,CONF_Sum,CONF_WAC,CONF_WCC
0,40,33,123.3,94.9,0.9531,52.6,48.1,15.4,18.2,40.7,30.0,32.3,30.4,53.9,44.6,32.7,36.2,71.7,8.6,2ND,1.0,2016,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
1,40,36,129.1,93.6,0.9758,54.8,47.7,12.4,15.8,32.1,23.7,36.2,22.4,54.8,44.7,36.5,37.5,59.3,11.3,2ND,1.0,2015,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
2,40,33,114.4,90.4,0.9375,53.9,47.7,14.0,19.5,25.5,24.9,30.7,30.0,54.7,46.8,35.2,33.2,65.9,6.9,2ND,3.0,2018,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
3,38,31,115.2,85.2,0.9696,53.5,43.0,17.7,22.8,27.4,28.7,32.9,36.6,52.8,41.9,36.5,29.7,67.5,7.0,2ND,3.0,2019,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
4,39,37,117.8,86.3,0.9728,56.6,41.1,16.2,17.1,30.0,26.2,39.0,26.9,56.3,40.0,38.2,29.0,71.5,7.7,2ND,1.0,2017,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1

In [ ]:
X["POSTSEASON"].unique()

<StringArray>
['2ND', 'Champions', 'E8', 'F4', 'R32', 'R64', 'R68', 'S16']
Length: 8, dtype: str

In [ ]:
tourney = {
    "Champions": (6, 6),   # played 6, won 6
    "2ND":       (6, 5),   # played 6, won 5 (lost the final)
    "F4":        (5, 4),   # lost in the national semifinal
    "E8":        (4, 3),
    "S16":       (3, 2),
    "R32":       (2, 1),
    "R64":       (1, 0),
    "R68":       (1, 0)
}

In [ ]:
X["t_games"] = X["POSTSEASON"].map({k: v[0] for k, v in tourney.items()})
X["t_wins"]  = X["POSTSEASON"].map({k: v[1] for k, v in tourney.items()})
X["t_games"] = X["t_games"].fillna(0)

In [ ]:
X.head()

,G,W,ADJOE,ADJDE,BARTHAG,EFG_O,EFG_D,TOR,TORD,ORB,DRB,FTR,FTRD,2P_O,2P_D,3P_O,3P_D,ADJ_T,WAB,POSTSEASON,SEED,YEAR,CONF_A10,CONF_ACC,CONF_AE,CONF_ASun,CONF_Amer,CONF_B10,CONF_B12,CONF_BE,CONF_BSky,CONF_BSth,CONF_BW,CONF_CAA,CONF_CUSA,CONF_Horz,CONF_Ivy,CONF_MAAC,CONF_MAC,CONF_MEAC,CONF_MVC,CONF_MWC,CONF_NEC,CONF_OVC,CONF_P12,CONF_Pat,CONF_SB,CONF_SC,CONF_SEC,CONF_SWAC,CONF_Slnd,CONF_Sum,CONF_WAC,CONF_WCC,t_games,t_wins
0,40,33,123.3,94.9,0.9531,52.6,48.1,15.4,18.2,40.7,30.0,32.3,30.4,53.9,44.6,32.7,36.2,71.7,8.6,2ND,1.0,2016,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,6,5
1,40,36,129.1,93.6,0.9758,54.8,47.7,12.4,15.8,32.1,23.7,36.2,22.4,54.8,44.7,36.5,37.5,59.3,11.3,2ND,1.0,2015,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,6,5
2,40,33,114.4,90.4,0.9375,53.9,47.7,14.0,19.5,25.5,24.9,30.7,30.0,54.7,46.8,35.2,33.2,65.9,6.9,2ND,3.0,2018,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,6,5
3,38,31,115.2,85.2,0.9696,53.5,43.0,17.7,22.8,27.4,28.7,32.9,36.6,52.8,41.9,36.5,29.7,67.5,7.0,2ND,3.0,2019,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,6,5
4,39,37,117.8,86.3,0.9728,56.6,41.1,16.2,17.1,30.0,26.2,39.0,26.9,56.3,40.0,38.2,29.0,71.5,7.7,2ND,1.0,2017,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,6,5

In [ ]:
X["G"] = X["G"] - X["t_games"]
X["W"] = X["W"] - X["t_wins"]

In [ ]:
X.head()

,G,W,ADJOE,ADJDE,BARTHAG,EFG_O,EFG_D,TOR,TORD,ORB,DRB,FTR,FTRD,2P_O,2P_D,3P_O,3P_D,ADJ_T,WAB,POSTSEASON,SEED,YEAR,CONF_A10,CONF_ACC,CONF_AE,CONF_ASun,CONF_Amer,CONF_B10,CONF_B12,CONF_BE,CONF_BSky,CONF_BSth,CONF_BW,CONF_CAA,CONF_CUSA,CONF_Horz,CONF_Ivy,CONF_MAAC,CONF_MAC,CONF_MEAC,CONF_MVC,CONF_MWC,CONF_NEC,CONF_OVC,CONF_P12,CONF_Pat,CONF_SB,CONF_SC,CONF_SEC,CONF_SWAC,CONF_Slnd,CONF_Sum,CONF_WAC,CONF_WCC,t_games,t_wins
0,34,28,123.3,94.9,0.9531,52.6,48.1,15.4,18.2,40.7,30.0,32.3,30.4,53.9,44.6,32.7,36.2,71.7,8.6,2ND,1.0,2016,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,6,5
1,34,31,129.1,93.6,0.9758,54.8,47.7,12.4,15.8,32.1,23.7,36.2,22.4,54.8,44.7,36.5,37.5,59.3,11.3,2ND,1.0,2015,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,6,5
2,34,28,114.4,90.4,0.9375,53.9,47.7,14.0,19.5,25.5,24.9,30.7,30.0,54.7,46.8,35.2,33.2,65.9,6.9,2ND,3.0,2018,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,6,5
3,32,26,115.2,85.2,0.9696,53.5,43.0,17.7,22.8,27.4,28.7,32.9,36.6,52.8,41.9,36.5,29.7,67.5,7.0,2ND,3.0,2019,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,6,5
4,33,32,117.8,86.3,0.9728,56.6,41.1,16.2,17.1,30.0,26.2,39.0,26.9,56.3,40.0,38.2,29.0,71.5,7.7,2ND,1.0,2017,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,6,5

In [ ]:
X["G"].unique()

array([34, 32, 33, 31, 35, 30, 27, 29, 28, 20, 18, 21, 25, 24, 19, 23, 26,
       22, 14, 16, 36])

In [ ]:
X["G"].value_counts()

G
32    185
33    185
34    160
31     97
30     45
29     30
35     21
28     17
27     15
25     12
23      9
21      7
24      7
20      6
26      6
19      4
22      4
18      3
14      1
16      1
36      1
Name: count, dtype: int64

In [ ]:
X[X["G"] >= 37][[ "YEAR", "POSTSEASON", "G", "W"]]

Empty DataFrame
Columns: [YEAR, POSTSEASON, G, W]
Index: []

In [ ]:
X["champion"] = (X["POSTSEASON"] == "Champions").astype(int)

In [ ]:
X["champion"].value_counts()

champion
0    804
1     12
Name: count, dtype: int64

In [ ]:
X = X.drop(columns=["POSTSEASON", "t_games", "t_wins"])

In [ ]:
train = X[X["YEAR"] <= 2021]
test  = X[X["YEAR"] >= 2022]

In [ ]:
train.head()

,G,W,ADJOE,ADJDE,BARTHAG,EFG_O,EFG_D,TOR,TORD,ORB,DRB,FTR,FTRD,2P_O,2P_D,3P_O,3P_D,ADJ_T,WAB,SEED,YEAR,CONF_A10,CONF_ACC,CONF_AE,CONF_ASun,CONF_Amer,CONF_B10,CONF_B12,CONF_BE,CONF_BSky,CONF_BSth,CONF_BW,CONF_CAA,CONF_CUSA,CONF_Horz,CONF_Ivy,CONF_MAAC,CONF_MAC,CONF_MEAC,CONF_MVC,CONF_MWC,CONF_NEC,CONF_OVC,CONF_P12,CONF_Pat,CONF_SB,CONF_SC,CONF_SEC,CONF_SWAC,CONF_Slnd,CONF_Sum,CONF_WAC,CONF_WCC,champion
0,34,28,123.3,94.9,0.9531,52.6,48.1,15.4,18.2,40.7,30.0,32.3,30.4,53.9,44.6,32.7,36.2,71.7,8.6,1.0,2016,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
1,34,31,129.1,93.6,0.9758,54.8,47.7,12.4,15.8,32.1,23.7,36.2,22.4,54.8,44.7,36.5,37.5,59.3,11.3,1.0,2015,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
2,34,28,114.4,90.4,0.9375,53.9,47.7,14.0,19.5,25.5,24.9,30.7,30.0,54.7,46.8,35.2,33.2,65.9,6.9,3.0,2018,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
3,32,26,115.2,85.2,0.9696,53.5,43.0,17.7,22.8,27.4,28.7,32.9,36.6,52.8,41.9,36.5,29.7,67.5,7.0,3.0,2019,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
4,33,32,117.8,86.3,0.9728,56.6,41.1,16.2,17.1,30.0,26.2,39.0,26.9,56.3,40.0,38.2,29.0,71.5,7.7,1.0,2017,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0

In [ ]:
exclude = ["champion"]
feature_cols = [c for c in X.columns if c not in exclude]
print(feature_cols)

['G', 'W', 'ADJOE', 'ADJDE', 'BARTHAG', 'EFG_O', 'EFG_D', 'TOR', 'TORD', 'ORB', 'DRB', 'FTR', 'FTRD', '2P_O', '2P_D', '3P_O', '3P_D', 'ADJ_T', 'WAB', 'SEED', 'YEAR', 'CONF_A10', 'CONF_ACC', 'CONF_AE', 'CONF_ASun', 'CONF_Amer', 'CONF_B10', 'CONF_B12', 'CONF_BE', 'CONF_BSky', 'CONF_BSth', 'CONF_BW', 'CONF_CAA', 'CONF_CUSA', 'CONF_Horz', 'CONF_Ivy', 'CONF_MAAC', 'CONF_MAC', 'CONF_MEAC', 'CONF_MVC', 'CONF_MWC', 'CONF_NEC', 'CONF_OVC', 'CONF_P12', 'CONF_Pat', 'CONF_SB', 'CONF_SC', 'CONF_SEC', 'CONF_SWAC', 'CONF_Slnd', 'CONF_Sum', 'CONF_WAC', 'CONF_WCC']

In [ ]:
y = X
y = y.drop(columns = feature_cols)
y.head()
X = X.drop(columns = "champion")

In [ ]:
X_train, y_train = train[feature_cols], train["champion"]
X_test,  y_test  = test[feature_cols],  test["champion"]

In [ ]:
clf_xgb = xgb.XGBClassifier(
    objective="binary:logistic",
    eval_metric="aucpr",
    n_estimators=300, max_depth=3, learning_rate=0.05,
    random_state=42,
)
clf_xgb.fit(X_train, y_train,   # deliberately left for you — see below
            verbose=True)

XGBClassifier(base_score=None, booster=None, callbacks=None,
              colsample_bylevel=None, colsample_bynode=None,
              colsample_bytree=None, device=None, early_stopping_rounds=None,
              enable_categorical=True, eval_metric='aucpr', feature_types=None,
              feature_weights=None, gamma=None, grow_policy=None,
              importance_type=None, interaction_constraints=None,
              learning_rate=0.05, max_bin=None, max_cat_threshold=None,
              max_cat_to_onehot=None, max_delta_step=None, max_depth=3,
              max_leaves=None, min_child_weight=None, missing=nan,
              monotone_constraints=None, multi_strategy=None, n_estimators=300,
              n_jobs=None, num_parallel_tree=None, ...)

In [ ]:
df_raw = pd.read_csv("cbb.csv")   # if you don't already have it loaded

results = test[["YEAR", "champion"]].copy()
results["TEAM"] = df_raw.loc[test.index, "TEAM"]
results["prob"] = clf_xgb.predict_proba(X_test)[:, 1]

for year, season in results.groupby("YEAR"):
    ranked = season.sort_values("prob", ascending=False).reset_index(drop=True)
    top_pick = ranked.loc[0, "TEAM"]
    champ_rank = ranked.index[ranked["champion"] == 1][0] + 1  # +1: rank 1 = best
    champ_name = ranked.loc[champ_rank - 1, "TEAM"]
    print(f"{year}: model's #1 = {top_pick:<20} | real champion = {champ_name:<20} ranked #{champ_rank}")

2022: model's #1 = Kansas               | real champion = Kansas               ranked #1
2023: model's #1 = Connecticut          | real champion = Connecticut          ranked #1
2024: model's #1 = Houston              | real champion = Connecticut          ranked #2
2025: model's #1 = Houston              | real champion = Florida              ranked #3

In [ ]:
results["POSTSEASON"] = df_raw.loc[test.index, "POSTSEASON"]
f4_labels = {"Champions", "2ND", "F4"}
results["made_f4"] = results["POSTSEASON"].isin(f4_labels)

for year, season in results.groupby("YEAR"):
    ranked = season.sort_values("prob", ascending=False)
    model_top4 = set(ranked.head(4)["TEAM"])
    real_f4 = set(season[season["made_f4"]]["TEAM"])
    hits = model_top4 & real_f4          # set intersection
    print(f"{year}: model top 4 = {sorted(model_top4)}")
    print(f"      real F4     = {sorted(real_f4)}")
    print(f"      overlap: {len(hits)}/4 {sorted(hits)}\n")

2022: model top 4 = ['Connecticut', 'Houston', 'Kansas', 'Tennessee']
      real F4     = ['Duke', 'Kansas', 'North Carolina', 'Villanova']
      overlap: 1/4 ['Kansas']

2023: model top 4 = ['Connecticut', 'Michigan St.', 'UCLA', 'Xavier']
      real F4     = ['Connecticut', 'Florida Atlantic', 'Miami FL', 'San Diego St.']
      overlap: 1/4 ['Connecticut']

2024: model top 4 = ['Connecticut', 'Houston', 'Kentucky', 'Purdue']
      real F4     = ['Alabama', 'Connecticut', 'North Carolina St.', 'Purdue']
      overlap: 2/4 ['Connecticut', 'Purdue']

2025: model top 4 = ['Auburn', 'Duke', 'Florida', 'Houston']
      real F4     = ['Auburn', 'Duke', 'Florida', 'Houston']
      overlap: 4/4 ['Auburn', 'Duke', 'Florida', 'Houston']